// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Kx4U7aekcxmcVEoNP-QRd2UN_O1NOug',
    appId: '1:107273341539:web:90b214d513f449a0f4c656',
    messagingSenderId: '107273341539',
    projectId: 'fluttter-firebase-a1ca3',
    authDomain: 'fluttter-firebase-a1ca3.firebaseapp.com',
    storageBucket: 'fluttter-firebase-a1ca3.appspot.com',
    measurementId: 'G-YW2X87MHC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hvPzC3Z9MircNRdMpDKerwFYbwn07Qw',
    appId: '1:107273341539:android:bfbe5176ea92628ff4c656',
    messagingSenderId: '107273341539',
    projectId: 'fluttter-firebase-a1ca3',
    storageBucket: 'fluttter-firebase-a1ca3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4OIXTsgXLSZbKyjitCmJal-grDW9oE8',
    appId: '1:107273341539:ios:e8d0a5424c3cb96cf4c656',
    messagingSenderId: '107273341539',
    projectId: 'fluttter-firebase-a1ca3',
    storageBucket: 'fluttter-firebase-a1ca3.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC4OIXTsgXLSZbKyjitCmJal-grDW9oE8',
    appId: '1:107273341539:ios:394021e3dda961c4f4c656',
    messagingSenderId: '107273341539',
    projectId: 'fluttter-firebase-a1ca3',
    storageBucket: 'fluttter-firebase-a1ca3.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
